version: "3.8"
services:
  envoy:
    build: ./compose/envoy
    ports:
      - "8080:80"
      - "8001:8001"
    volumes:
      - ./envoy.yaml:/config/envoy.yaml
    environment:
      - DEBUG_LEVEL=debug
      - SERVICE_NAME=app
      - SERVICE_PORT=8500

  opa:
    image: openpolicyagent/opa:0.23.0-envoy # 0.21.1-istio or 0.22.0-envoy
    ports:
      - "8181:8181"
    volumes:
      - ./policy.rego:/config/policy.rego
    command:
      - "run"
      - "--log-level=debug"
      - "--server"
      - "--set=plugins.envoy_ext_authz_grpc.addr=:9191"
      - "--set=decision_logs.console=true"
      - "/config/policy.rego"

  app:
    build: ./compose/hoverfly
    #image: spectolabs/hoverfly:v1.3.0
    ports:
      - "8888:8888"
      - "8500:8500"
    #volumes:
    #  - ./hoverfly:/hoverfly
    command:
      - "-webserver"
      - "-logs-output"
      - "console"
      - "-import"
      - "/hoverfly/config.json"
      - "-logs"
      - "json"
      - "-log-level"
      - "debug"
